---
version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:715841367723:task-definition/project6-task:1"
        LoadBalancerInfo:
          ContainerName: "python-app"
          ContainerPort: 5000
